version: '3.8'

services:
  # API Backend
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=eo_chatbot
    depends_on:
      - mongodb
    networks:
      - eo-chatbot-network

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - eo-chatbot-network

  # MongoDB Database
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - eo-chatbot-network
    environment:
      - MONGO_INITDB_DATABASE=eo_chatbot
    command: --wiredTigerCacheSizeGB 1.0  # Reduce memory usage for development

  # Admin Dashboard (Streamlit)
  admin:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: python scripts/run_admin.py
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=eo_chatbot
    depends_on:
      - mongodb
    networks:
      - eo-chatbot-network

networks:
  eo-chatbot-network:
    driver: bridge

volumes:
  mongodb_data: